apiVersion: v1

kind: Service

metadata:
  name: chatbot-service
  labels:
    app: chatbot-app

spec:
  type: NodePort
  selector:
    app: chatbot-app
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30008



  